"""
Monitoring tools for the On-call agent: queries the project's own JSONL
trace files (the same files tracing.py writes for every agent run) and
makes lightweight HTTP health checks.

query_traces deliberately reads the system's own operational logs rather
than a fabricated "production log" concept — there's no real deployed
service for this portfolio project to monitor, but there IS real
operational data already being generated by every other agent run, and
that's exactly the kind of thing an on-call engineer would actually look
at: which tasks failed, which tool calls got blocked, where the errors
were. This is the same data Phase 2 built for the dashboard, now also
queryable by an agent.
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from pathlib import Path

from ..config import get_config
from .registry import tool

_MAX_RESULT_CHARS = 5_000
_HEALTH_CHECK_TIMEOUT_SECONDS = 5


@tool(
    name="query_traces",
    description=(
        "Search the project's own JSONL trace files (one per task, under the trace "
        "directory) for errors, blocked guardrail violations, or events matching a "
        "filter. Use this to investigate what happened in a previous agent run."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "task_id_prefix": {
                "type": "string",
                "description": "Only look at trace files whose task_id starts with this. "
                "Empty string for all.",
            },
            "event_type": {
                "type": "string",
                "description": (
                    "Only return records of this type: llm_call, llm_error, tool_call, "
                    "task_end. Empty string for all types."
                ),
            },
            "errors_only": {
                "type": "boolean",
                "description": "If true, only return records where is_error or blocked is "
                "true, or type is llm_error.",
            },
        },
        "required": [],
    },
)
def query_traces(task_id_prefix: str = "", event_type: str = "", errors_only: bool = False) -> str:
    trace_dir = Path(get_config().trace_dir)
    if not trace_dir.is_dir():
        return "No trace directory found — no agent runs have happened yet."

    matches = []
    for path in sorted(trace_dir.glob(f"{task_id_prefix}*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            if event_type and record.get("type") != event_type:
                continue
            if errors_only and not (
                record.get("is_error") or record.get("blocked") or record.get("type") == "llm_error"
            ):
                continue
            matches.append(record)

    if not matches:
        return "No matching trace records found."

    output = json.dumps(matches, default=str)
    if len(output) > _MAX_RESULT_CHARS:
        output = output[:_MAX_RESULT_CHARS] + "...[truncated]"
    return output


@tool(
    name="health_check",
    description="Make an HTTP GET request to a URL and report its status code and response time.",
    input_schema={
        "type": "object",
        "properties": {"url": {"type": "string", "description": "Full http(s) URL to check"}},
        "required": ["url"],
    },
)
def health_check(url: str) -> str:
    if not url.startswith(("http://", "https://")):
        raise ValueError("health_check only supports http:// and https:// URLs")

    start = time.monotonic()
    try:
        with urllib.request.urlopen(url, timeout=_HEALTH_CHECK_TIMEOUT_SECONDS) as response:
            elapsed = time.monotonic() - start
            return f"status={response.status} elapsed_seconds={elapsed:.3f}"
    except urllib.error.HTTPError as exc:
        elapsed = time.monotonic() - start
        # A non-2xx response is informative output for an on-call agent,
        # not a tool-execution failure — return it rather than raise.
        return f"status={exc.code} elapsed_seconds={elapsed:.3f} (HTTP error response)"
    except Exception as exc:
        elapsed = time.monotonic() - start
        return f"error={exc} elapsed_seconds={elapsed:.3f} (could not connect)"
